# Generated by Django 2.2.13 on 2021-12-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('existencias', models.IntegerField(default=0)),
                ('vencimiento', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubi', to='api.Ubicacion')),
                ('estanteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estan', to='api.Estanteria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='api.Producto')),
            ],
        ),
    ]
