# Generated by Django 2.2.13 on 2021-12-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_detalleproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='vencimiento',
            field=models.CharField(max_length=50),
        ),
    ]
