# Generated by Django 2.2.13 on 2021-12-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211210_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='existenciasT',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fardos', models.IntegerField(default=0)),
                ('total_costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('detalleproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_venta', to='api.DetalleProducto')),
            ],
        ),
    ]
