# Generated by Django 2.2.13 on 2021-12-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211223_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='vencimiento',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
