# Generated by Django 2.2.13 on 2022-01-14 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_detalleproducto_estanteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='almacen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubi', to='api.Ubicacion'),
        ),
    ]
