# Generated by Django 2.2.13 on 2022-03-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
