# Generated by Django 2.2.13 on 2022-05-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_abonocredito_credito_detallecredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
